# Cheat config file conf.yml:
cheatpaths:
  - name: vim
    path: ~/.vim/bundle/vim.config/docs  # this is a separate directory and repository than above
    tags: [ vim ]
    readonly: false                   # new sheets may be written here

  - name: personal
    path: ~/dotwiki/cheat             # this is a separate directory and repository than above
    tags: [ personal ]
    readonly: false                   # new sheets may be written here

  - name: wiki
    path: ~/wiki/cheat                # this is a separate directory and repository than above
    tags: [ wiki ]
    readonly: false                   # new sheets may be written here

  - name: community                   # a name for the cheatpath
    path: ~/Documents/cheatsheets     # the path's location on the filesystem
    tags: [ community ]               # these tags will be applied to all sheets on the path
    readonly: true                    # if true, `cheat` will not create new cheatsheets here

