---
# Root layout
layout: even-vertical

# Root window options
pane-border-status: top

# List of windows
windows:
  ## The 1st window: Name only, no panes
  #- empty, named window

  - {{ $heyWindow }}:       # Name of the window
      layout: tiled         # Window layout, overrides root layout
      panes:                # List of panes
        - '[build]':
          - mkdir -p {{ $HOME }}/work/{{ $heyWindow }}
          - cd {{ $HOME }}/work/{{ $heyWindow }}
        - '[model]':
          - sleep 1
          - cd {{ $HOME }}/work/{{ $heyWindow }}
        - '[doc]':
          - sleep 1
          - cd {{ $HOME }}/work/{{ $heyWindow }}
          - new-doc.sh {{ $heyBug }}
        - '[main]':
          - sleep 1
          - cd {{ $HOME }}/work/{{ $heyWindow }}
          - df -hm
          - tmux select-pane -t 2

