#!/bin/bash

curDir=$(pwd)
tmux killp -a; tmex $(tmux display-message -p '#S') -w $(tmux display-message -p '#W') -t -l {15}31 "cd $curDir; reset" "cd $curDir; reset" "cd $curDir; reset" "cd $curDir; reset"
